name: Dart CI

on: [push]

jobs: 
  build:
    #if conditional to prevent a job from running
    if: github.event_name != 'pull_request'
    runs-on: macos-latest
    #Identifies any jobs that must complete successfully before this job will run.
    name: Build  apk  and web
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      #enable linux,macos,windows   and  web
      - run: flutter pub get
      # build macOS desktop version
      - run: flutter build ios
      # build Android version
      - run: flutter build appbundle
