name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: flutter pub get


    - name: run tests
      uses: steebchen/flutter@v1.0.0
      with:
        args: test
